import wordmark from "../../../assets/balema_logo.png";

export const belemaBrand = {
  id: "belema",
  displayName: "Belema Financial Technology Limited",
  shortName: "Belema",
  tagline: "Switching Platform",
  meta: {
    documentTitle: "Belema Financial Technology Limited",
  },
  logos: {
    wordmark,
    icon: wordmark,
    alt: "Belema Financial Technology Limited",
  },
  images: {},
  routes: {
    accountsDashboard: "/dashboard/accounts",
    liveMonitoring: "/dashboard/live-monitoring",
  },
  menus: {
    groupLabels: {
      accounts: "Accounts",
      wallet: "Wallet",
      approvals: "Approvals",
      administration: "Administration",
    },
    dashboardLabels: {
      accounts: "Dashboard",
    },
  },
  productText: {
    shellSubtitle: "Switching Platform",
    /** Shown at the bottom of the main sidebar nav (below Administration). */
    sidebarBelowNavLabel: "Belema",
    accountsDashboardTitle: "Operations Dashboard",
    accountsDashboardDescription: "Account-based transaction monitoring and analytics",
    loginHeading: "Log in",
    activationPrompt: "Activate account",
  },
  theme: {
    background: "#ffffff",
    foreground: "#1f2937",
    card: "#ffffff",
    cardForeground: "#1f2937",
    popover: "#ffffff",
    popoverForeground: "#1f2937",
    primary: "#0f2e67",
    primaryForeground: "#ffffff",
    primaryHover: "#12387f",
    secondary: "#edf3fb",
    secondaryForeground: "#0f2e67",
    muted: "#f5f8fc",
    mutedForeground: "#334155",
    accent: "#dff0ff",
    accentForeground: "#0f2e67",
    destructive: "#d4183d",
    destructiveForeground: "#ffffff",
    border: "#d6e4f5",
    inputBackground: "#f7f9fc",
    switchBackground: "#bfd6ef",
    ring: "#2d8fe2",
    chart: ["#0f2e67", "#2d8fe2", "#f0a63a", "#d65252", "#4faef0"],
    sidebar: "#f2f5ef",
    sidebarForeground: "#2f3d2a",
    sidebarPrimary: "#d8e7c8",
    sidebarPrimaryForeground: "#2f3d2a",
    sidebarAccent: "#e8f0dc",
    sidebarAccentForeground: "#4a5c3a",
    sidebarBorder: "#d5e2c8",
    sidebarRing: "#a8c48a",
    shellSurface: "#f7f9fc",
    /** Login page colors from `balema_logo.png` (globe greens + charcoal plate). */
    loginSurface: "#b0d995",
    loginHero: "#1a1a1a",
    loginPrimary: "#548235",
    authPanelFrom: "#f5f5f5",
    authPanelVia: "#e8f5d9",
    authPanelTo: "#c8e6b0",
    leafPrimary: "rgba(168, 196, 138, 0.28)",
    leafSecondary: "rgba(216, 231, 200, 0.45)",
    leafTertiary: "rgba(122, 158, 96, 0.18)",
  },
  api: {
    baseUrlFallback: "http://localhost:8077/sparkpayapi",
  },
  mockBrand: {
    institutionName: "Belema Financial Technology Limited",
    organizationName: "Belema Operations",
    testEnvironmentName: "Belema Test Environment",
    emailDomain: "belema.ng",
    backupCodesFileName: "belema-backup-codes.txt",
    backupCodesLabel: "Belema - Backup codes (single use)",
    users: [
      {
        id: "U001",
        username: "admin_user",
        email: "admin@belema.ng",
        password: "Admin@123",
        phone: "+234 800 000 0001",
        roleName: "Admin",
        status: "Active",
        mustChangePassword: false,
      },
      {
        id: "U002",
        username: "approval_user",
        email: "approver@belema.ng",
        password: "Approver@123",
        phone: "+234 800 000 0002",
        roleName: "Approver",
        status: "Active",
        mustChangePassword: false,
      },
      {
        id: "U003",
        username: "ops_user",
        email: "operator@belema.ng",
        password: "Operator@123",
        phone: "+234 800 000 0003",
        roleName: "Operator",
        status: "Active",
        mustChangePassword: false,
      },
    ],
  },
};
